#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

eval "$(/opt/homebrew/bin/brew shellenv)"
source <(fzf --zsh)
alias vi='nvim'
alias vim='nvim'
alias gk='open -na "GitKraken" --args -p $(pwd)'
alias cljfmtns="bb --config /Users/rafal/Code/bloom-cljfmtns/bb.edn cljfmtns"
